CREATE TABLE [dbo].[Payments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [PartnerId] UNIQUEIDENTIFIER NOT NULL,
    [Account] NVARCHAR(50) NOT NULL,
    [Amount] DECIMAL(15, 4) NOT NULL,
    [CreatedDate] DATETIME NOT NULL,
    [CurrencyId] UNIQUEIDENTIFIER NOT NULL
)
